import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const seed=[
{id:'demo1',username:'KUZU Bhutan',userId:'demo',caption:'Welcome to KUZU 🇧🇹',tags:'#Bhutan #KUZU',likes:124,comments:18,media:'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',demo:true,visibility:'public'},
{id:'demo2',username:'Mountain Life',userId:'demo2',caption:'A little Bhutan every day.',tags:'#Bhutan #Nature',likes:89,comments:9,media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',demo:true,visibility:'public'},
{id:'demo3',username:'Kuzu Creator',userId:'demo3',caption:'Your next video could be here.',tags:'#KUZU #ForYou',likes:52,comments:6,media:'https://www.w3schools.com/html/mov_bbb.mp4',demo:true,visibility:'public'}
];
const LIVE_GIFTS=[
 {id:'red-panda',name:'Red Panda',icon:'🦊',cost:5},
 {id:'blue-poppy',name:'Blue Poppy',icon:'🌸',cost:5},
 {id:'takin',name:'Takin',icon:'🐂',cost:10},
 {id:'prayer-flags',name:'Prayer Flags',icon:'🎏',cost:15},
 {id:'butter-lamp',name:'Butter Lamp',icon:'🪔',cost:15},
 {id:'gho-kira',name:'Gho & Kira',icon:'🥋',cost:20},
 {id:'ema-datshi',name:'Ema Datshi',icon:'🌶️',cost:20},
 {id:'chhang',name:'Chhang',icon:'🥛',cost:20},
 {id:'basket',name:'Bamboo Basket',icon:'🧺',cost:25},
 {id:'tsechu-mask',name:'Tsechu Mask',icon:'🎭',cost:30},
 {id:'yak',name:'Yak',icon:'🐃',cost:35},
 {id:'tashi-delek',name:'Tashi Delek',icon:'✨',cost:50},
 {id:'chorten',name:'Chorten',icon:'🛕',cost:60},
 {id:'khata',name:'Khata',icon:'🤍',cost:75},
 {id:'mountains',name:'Himalayan Peaks',icon:'🏔️',cost:100},
 {id:'guru',name:'Guru Rinpoche',icon:'🙏',cost:150},
 {id:'taktsang',name:'Taktsang',icon:'🏔️',cost:250},
 {id:'druk',name:'Thunder Dragon',icon:'🐉',cost:500},
 {id:'snow-lion',name:'Snow Lion',icon:'🦁',cost:750},
 {id:'royal-dragon',name:'Royal Dragon',icon:'🐲',cost:1000},
];

const api=async(path,opts={})=>{const r=await fetch('/api/'+path,{credentials:'include',...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Request failed');return d};
const deviceId=(()=>{let v=localStorage.getItem('kuzuDeviceId');if(!v){v=crypto.randomUUID();localStorage.setItem('kuzuDeviceId',v)}return v})();
const jsonHeaders={'content-type':'application/json','x-kuzu-device':deviceId};

function App(){
 const [user,setUser]=useState(null),[videos,setVideos]=useState([]),[tab,setTab]=useState('forYou'),[search,setSearch]=useState(''),[query,setQuery]=useState('');
 const [modal,setModal]=useState(null),[authChallenge,setAuthChallenge]=useState(''),[resetToken,setResetToken]=useState(''),[notice,setNotice]=useState(''),[liked,setLiked]=useState({}),[following,setFollowing]=useState({});
 const [commentsFor,setCommentsFor]=useState(null),[comments,setComments]=useState([]),[profile,setProfile]=useState(null),[notifications,setNotifications]=useState([]),[messages,setMessages]=useState([]),[activeChat,setActiveChat]=useState(null),[chatMessages,setChatMessages]=useState([]);
 const [liveRoom,setLiveRoom]=useState(null),[liveGiftLog,setLiveGiftLog]=useState([]),[liveMode,setLiveMode]=useState('camera');
 useEffect(()=>{api('auth/me').then(x=>setUser(x.user)).catch(()=>{});loadVideos()},[]);
 useEffect(()=>{const fn=()=>setModal('security');window.addEventListener('kuzu-security',fn);return()=>window.removeEventListener('kuzu-security',fn)},[]);
 useEffect(()=>{if(!user)return;if(tab==='notifications')api('notifications').then(x=>setNotifications(x.notifications)).catch(()=>{});if(tab==='messages')api('messages').then(x=>setMessages(x.messages)).catch(()=>{});if(tab==='profile')api('profile').then(setProfile).catch(()=>{})},[tab,user]);
 async function loadVideos(q='',followingOnly=false){try{const qs=[];if(q)qs.push(`q=${encodeURIComponent(q)}`);if(followingOnly)qs.push('following=1');const d=await api('videos'+(qs.length?'?'+qs.join('&'):''));setVideos(d.videos.length?d.videos:seed)}catch{setVideos(seed)}}
 const shown=useMemo(()=>videos.filter(v=>!query||`${v.username} ${v.caption} ${v.tags} ${v.location||''}`.toLowerCase().includes(query.toLowerCase())),[videos,query]);
 function flash(x){setNotice(x);setTimeout(()=>setNotice(''),2800)}
 useEffect(()=>{const q=new URLSearchParams(location.search);const verify=q.get('verify'),reset=q.get('reset');if(verify){api('auth/verify-email',{method:'POST',headers:jsonHeaders,body:JSON.stringify({token:verify})}).then(d=>{setUser(d.user);history.replaceState({},'',location.pathname);flash('Email verified. Welcome to KUZU 🇧🇹')}).catch(e=>{history.replaceState({},'',location.pathname);flash(e.message)})}else if(reset){setResetToken(reset);setModal('reset');history.replaceState({},'',location.pathname+'?reset=1')}},[]);
 async function like(v){if(!user)return setModal('auth');if(v.demo){setLiked(x=>({...x,[v.id]:!x[v.id]}));setVideos(xs=>xs.map(x=>x.id===v.id?{...x,likes:Math.max(0,x.likes+(liked[v.id]?-1:1))}:x));return;}try{const d=await api('like',{method:'POST',headers:jsonHeaders,body:JSON.stringify({videoId:v.id})});setLiked(x=>({...x,[v.id]:d.liked}));setVideos(xs=>xs.map(x=>x.id===v.id?{...x,likes:d.likes}:x))}catch(e){flash(e.message)}}
 async function follow(v){if(!user)return setModal('auth');if(v.demo){setFollowing(x=>({...x,[v.userId]:!x[v.userId]}));return;}try{const d=await api('follow',{method:'POST',headers:jsonHeaders,body:JSON.stringify({userId:v.userId})});setFollowing(x=>({...x,[v.userId]:d.following}));flash(d.following?'Following creator':'Unfollowed creator')}catch(e){flash(e.message)}}
 async function openComments(v){if(!user)return setModal('auth');setCommentsFor(v);if(v.demo){setComments([]);return;}try{setComments((await api(`comments/${v.id}`)).comments)}catch{setComments([])}}
 async function addComment(e){e.preventDefault();if(!user)return setModal('auth');const text=e.target.text.value.trim();if(!text)return;if(commentsFor?.demo){const c={id:crypto.randomUUID(),username:user.username,text,createdAt:new Date().toISOString()};setComments(x=>[...x,c]);setVideos(xs=>xs.map(x=>x.id===commentsFor.id?{...x,comments:x.comments+1}:x));e.target.reset();return;}try{const d=await api(`comments/${commentsFor.id}`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({text})});setComments(x=>[...x,d.comment]);setVideos(xs=>xs.map(x=>x.id===commentsFor.id?{...x,comments:x.comments+1}:x));e.target.reset()}catch(err){flash(err.message)}}
 async function submitAuth(e){e.preventDefault();const fd=new FormData(e.currentTarget);const mode=e.currentTarget.dataset.mode||(modal==='signup'?'signup':'login');try{const endpoint=mode==='signup'?'auth/register':mode==='forgot'?'auth/forgot-password':'auth/login';const d=await api(endpoint,{method:'POST',headers:jsonHeaders,body:JSON.stringify(Object.fromEntries(fd))});if(mode==='forgot'){setModal(null);flash(d.message||'Check your email for a reset link.');return}if(d.requiresVerification){setModal(null);flash('Account created. Check your email to verify your account.');return}if(d.requires2FA){setAuthChallenge(d.challenge);setModal('twofa');return}setUser(d.user);setModal(null);flash('Welcome to KUZU 🇧🇹')}catch(err){flash(err.message)}}
 async function finishTwoFA(code){try{const d=await api('auth/2fa/verify',{method:'POST',headers:jsonHeaders,body:JSON.stringify({challenge:authChallenge,code})});setUser(d.user);setAuthChallenge('');setModal(null);flash('Signed in securely.')}catch(e){flash(e.message)}}
 async function resetPassword(password){try{await api('auth/reset-password',{method:'POST',headers:jsonHeaders,body:JSON.stringify({token:resetToken,password})});setModal('auth');setResetToken('');flash('Password changed. You can sign in now.')}catch(e){flash(e.message)}}
 async function logout(){await api('auth/logout',{method:'POST'});setUser(null);setProfile(null);setTab('forYou');flash('Signed out')}
 async function upload(e){e.preventDefault();if(!user)return setModal('auth');const fd=new FormData(e.currentTarget);fd.set('visibility',e.currentTarget.dataset.visibility||'public');const f=fd.get('video');if(!f?.size)return;if(f.size>5_000_000)return flash('Current free deployment upload limit is 5 MB. Large-video storage is ready for the next direct-upload connection.');try{await api('videos',{method:'POST',body:fd});setModal(null);await loadVideos();flash('Video posted!')}catch(err){flash(err.message)}}
 async function openChat(uid){setActiveChat(uid);try{setChatMessages((await api(`messages/${uid}`)).messages)}catch{setChatMessages([])}}
 async function sendMessage(e){e.preventDefault();const text=e.target.text.value.trim();if(!text||!activeChat)return;try{const d=await api('messages',{method:'POST',headers:jsonHeaders,body:JSON.stringify({to:activeChat,text})});setChatMessages(x=>[...x,d.message]);e.target.reset();}catch(err){flash(err.message)}}
 function doSearch(e){e.preventDefault();setQuery(search.trim());setTab('forYou');loadVideos(search.trim())}
 return <div className="app">
  <header><button className="brand" onClick={()=>{setTab('forYou');setQuery('')}}>KUZU <span>🇧🇹</span></button><form className="search" onSubmit={doSearch}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search KUZU"/><button>Enter</button></form>{user?<button className="profileTop" onClick={()=>setTab('profile')}>@{user.username}</button>:<button className="login" onClick={()=>setModal('auth')}>Sign in</button>}</header>
  <main>{tab==='live'?<LiveHub user={user} onLogin={()=>setModal('auth')} onStart={()=>user?setModal('liveStudio'):setModal('auth')} onWatch={(room)=>setLiveRoom(room)} liveRoom={liveRoom} liveGiftLog={liveGiftLog}/>:tab==='profile'&&user?<Profile user={user} data={profile} onLogout={logout}/>:tab==='notifications'&&user?<Notifications items={notifications}/>:tab==='messages'&&user?<Messages people={messages} activeChat={activeChat} chatMessages={chatMessages} onOpen={openChat} onSend={sendMessage}/>:<div className="feed">{shown.map(v=><VideoCard key={v.id} v={v} liked={liked[v.id]} following={following[v.userId]} onLike={like} onFollow={follow} onComments={openComments} onMessage={()=>user?openChat(v.userId):setModal('auth')} onReport={async()=>{if(v.demo)return flash('Demo video.');if(!user)return setModal('auth');try{await api('report',{method:'POST',headers:jsonHeaders,body:JSON.stringify({videoId:v.id,reason:'Reported by user'})});flash('Report submitted')}catch(e){flash(e.message)}}}/>)}</div>}</main>
  <nav><button className={tab==='forYou'?'sel':''} onClick={()=>{setTab('forYou');loadVideos()}}>⌂<span>For You</span></button><button className={tab==='live'?'sel':''} onClick={()=>setTab('live')}>🔴<span>Live</span></button><button className="create" onClick={()=>user?setModal('upload'):setModal('auth')}>＋</button><button className={tab==='messages'?'sel':''} onClick={()=>user?setTab('messages'):setModal('auth')}>💬<span>Messages</span></button><button className={tab==='notifications'?'sel':''} onClick={()=>user?setTab('notifications'):setModal('auth')}>🔔<span>Alerts</span></button><button className={tab==='profile'?'sel':''} onClick={()=>user?setTab('profile'):setModal('auth')}>◯<span>Profile</span></button></nav>
  {modal==='auth'&&<Auth onSubmit={submitAuth} onClose={()=>setModal(null)}/>} {modal==='twofa'&&<TwoFactorLogin onSubmit={finishTwoFA} onClose={()=>{setAuthChallenge('');setModal(null)}}/>} {modal==='reset'&&<ResetPassword onSubmit={resetPassword} onClose={()=>setModal(null)}/>} {modal==='security'&&<Security onClose={()=>setModal(null)} onNotice={flash}/>}  {modal==='upload'&&<Upload onSubmit={upload} onClose={()=>setModal(null)}/>} {modal==='liveStudio'&&<LiveStudio user={user} mode={liveMode} setMode={setLiveMode} onClose={()=>setModal(null)} onStarted={(room)=>{setModal(null);setLiveRoom(room);setTab('live')}} onNotice={flash}/>} {commentsFor&&<Comments v={commentsFor} comments={comments} onSubmit={addComment} onClose={()=>setCommentsFor(null)} user={user}/>} {notice&&<div className="toast">{notice}</div>}
 </div>
}
function VideoCard({v,liked,following,onLike,onFollow,onComments,onMessage,onReport}){const ref=useRef();useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(es=>es.forEach(x=>x.isIntersecting?el.play().catch(()=>{}):el.pause()),{threshold:.65});io.observe(el);return()=>io.disconnect()},[]);return <article className="video"><video ref={ref} src={v.media} playsInline muted loop controls={false}/><div className="shade"/><div className="info"><b>@{v.username}</b><p>{v.caption}</p><small>{v.tags}</small>{v.location&&<small>📍 {v.location}</small>}</div><div className="actions"><button onClick={()=>onLike(v)}>♥<small>{v.likes}</small></button><button onClick={()=>onComments(v)}>💬<small>{v.comments}</small></button><button onClick={()=>navigator.share?navigator.share({title:'KUZU',text:v.caption,url:location.href}).catch(()=>{}):navigator.clipboard?.writeText(location.href)}>↗<small>Share</small></button><button onClick={()=>onFollow(v)}>{following?'✓':'+'}<small>{following?'Following':'Follow'}</small></button><button onClick={onMessage}>✉<small>Message</small></button><button onClick={onReport}>⚑<small>Report</small></button></div></article>}
function Auth({onSubmit,onClose}){const [mode,setMode]=useState('login');return <div className="modal"><form className="card" onSubmit={e=>{e.currentTarget.dataset.mode=mode;onSubmit(e)}}><button type="button" className="x" onClick={onClose}>×</button><h2>{mode==='signup'?'Create your KUZU account':mode==='forgot'?'Reset your password':'Welcome to KUZU'}</h2>{mode==='signup'?<><p>Join Bhutan’s short-video community.</p><input name="username" placeholder="Username" required/><input name="email" type="email" placeholder="Email" required/><input name="phone" type="tel" placeholder="Phone (optional)"/><input name="password" type="password" placeholder="Password (10+ characters)" minLength="10" required/><button className="primary">Create account</button><button type="button" className="ghost" onClick={()=>setMode('login')}>Already have an account? Sign in</button></>:mode==='forgot'?<><p>Enter your email and we’ll send a secure reset link.</p><input name="email" type="email" placeholder="Email" required/><button className="primary">Send reset link</button><button type="button" className="ghost" onClick={()=>setMode('login')}>Back to sign in</button></>:<><p>Sign in to like, follow, message, comment and post.</p><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength="10" required/><button className="primary">Sign in</button><button type="button" className="ghost" onClick={()=>setMode('forgot')}>Forgot password?</button><button type="button" className="ghost" onClick={()=>setMode('signup')}>Need an account? Create one</button></>}</form></div>}
function TwoFactorLogin({onSubmit,onClose}){const [code,setCode]=useState('');return <div className="modal"><form className="card" onSubmit={e=>{e.preventDefault();onSubmit(code)}}><button type="button" className="x" onClick={onClose}>×</button><h2>🔐 Two-step verification</h2><p>Open your authenticator app and enter the 6-digit KUZU code.</p><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" maxLength="6" required/><button className="primary" disabled={code.length!==6}>Verify & sign in</button></form></div>}
function ResetPassword({onSubmit,onClose}){const [pw,setPw]=useState(''),[pw2,setPw2]=useState('');return <div className="modal"><form className="card" onSubmit={e=>{e.preventDefault();if(pw!==pw2)return alert('Passwords do not match');onSubmit(pw)}}><button type="button" className="x" onClick={onClose}>×</button><h2>Choose a new password</h2><input type="password" value={pw} onChange={e=>setPw(e.target.value)} minLength="10" placeholder="New password (10+ characters)" required/><input type="password" value={pw2} onChange={e=>setPw2(e.target.value)} minLength="10" placeholder="Repeat new password" required/><button className="primary">Change password</button></form></div>}
function Security({onClose,onNotice}){const [setup,setSetup]=useState(null),[code,setCode]=useState(''),[password,setPassword]=useState(''),[enabled,setEnabled]=useState(false),[loading,setLoading]=useState(true);useEffect(()=>{api('auth/me').then(d=>setEnabled(!!d.user?.twoFactorEnabled)).finally(()=>setLoading(false))},[]);async function start(){try{const d=await api('auth/2fa/setup',{method:'POST'});setSetup(d);onNotice('2FA setup started. Add the secret to your authenticator app.')}catch(e){onNotice(e.message)}}async function enable(){try{await api('auth/2fa/enable',{method:'POST',headers:jsonHeaders,body:JSON.stringify({code})});setEnabled(true);setSetup(null);setCode('');onNotice('Two-factor authentication is now enabled.')}catch(e){onNotice(e.message)}}async function disable(){try{await api('auth/2fa/disable',{method:'POST',headers:jsonHeaders,body:JSON.stringify({password})});setEnabled(false);setPassword('');onNotice('Two-factor authentication disabled.')}catch(e){onNotice(e.message)}}if(loading)return <div className="modal"><div className="card"><h2>Account security</h2><p>Loading security settings…</p></div></div>;return <div className="modal"><div className="card"><button className="x" onClick={onClose}>×</button><h2>🔐 Account security</h2><p className="muted">Email verification, password recovery and optional authenticator-based 2FA protect your account.</p><div className="securityRow"><b>Email verification</b><span>✓ Enabled for new accounts</span></div><div className="securityRow"><b>Two-factor authentication</b><span>{enabled?'✓ Enabled':'Not enabled'}</span></div>{!enabled&&!setup&&<button className="primary" onClick={start}>Enable 2FA</button>}{setup&&<div className="securitySetup"><p><b>1.</b> Add this secret to Google Authenticator, Microsoft Authenticator, Authy or another TOTP app.</p><code>{setup.secret}</code><p className="muted">If your app supports an otpauth link, use the URI below.</p><textarea readOnly value={setup.otpauthUri}/><p><b>2.</b> Enter the 6-digit code generated by your app.</p><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" placeholder="000000"/><button className="primary" onClick={enable}>Confirm & enable 2FA</button></div>}{enabled&&<div><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Current password to disable 2FA"/><button className="ghost" onClick={disable}>Disable 2FA</button></div>}<button className="ghost" onClick={onClose}>Close</button></div></div>}

const CAMERA_FILTERS=[
 {id:'normal',name:'Original',css:'none'},
 {id:'warm',name:'Warm Bhutan',css:'sepia(.18) saturate(1.18) contrast(1.05)'},
 {id:'cool',name:'Himalayan',css:'saturate(.9) contrast(1.08) hue-rotate(8deg)'},
 {id:'vivid',name:'Vivid',css:'saturate(1.5) contrast(1.08)'},
 {id:'cinema',name:'Cinema',css:'contrast(1.18) saturate(.82) brightness(.94)'},
 {id:'soft',name:'Soft Glow',css:'brightness(1.05) saturate(.92) contrast(.94)'}
];
const BHUTAN_MUSIC=[
 {id:'folk',title:'Bhutan Folk • Licensed Track',artist:'KUZU Music Library',kind:'Bhutan Trending'},
 {id:'druk-beat',title:'Druk Beat • Licensed Track',artist:'KUZU Music Library',kind:'Bhutan Trending'},
 {id:'mountain',title:'Himalayan Morning • Licensed Track',artist:'KUZU Music Library',kind:'Bhutan Trending'},
 {id:'festival',title:'Tsechu Festival • Licensed Track',artist:'KUZU Music Library',kind:'Bhutan Trending'},
 {id:'chill',title:'Bhutan Chill • Licensed Track',artist:'KUZU Music Library',kind:'Bhutan Trending'}
];
function Upload({onSubmit,onClose}){
 const [visibility,setVisibility]=useState('public'),[filter,setFilter]=useState('normal'),[music,setMusic]=useState('none'),[cameraOpen,setCameraOpen]=useState(false),[stream,setStream]=useState(null),[recording,setRecording]=useState(false),[recordedFile,setRecordedFile]=useState(null),[cameraVideo,setCameraVideo]=useState(null);
 const videoRef=useRef(null),canvasRef=useRef(null),recRef=useRef(null),chunksRef=useRef([]);
 const chosenFilter=CAMERA_FILTERS.find(x=>x.id===filter)||CAMERA_FILTERS[0];
 useEffect(()=>()=>{stream?.getTracks().forEach(t=>t.stop());if(cameraVideo)URL.revokeObjectURL(cameraVideo)},[stream,cameraVideo]);
 async function openCamera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera is not available in this browser/device.');const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:true});setStream(s);setCameraOpen(true);setTimeout(async()=>{if(videoRef.current){videoRef.current.srcObject=s;await videoRef.current.play().catch(()=>{})}},0)}catch(e){alert(e.message)}}
 function startRecording(){if(!stream||!videoRef.current||!canvasRef.current)return;const video=videoRef.current,canvas=canvasRef.current,ctx=canvas.getContext('2d');canvas.width=video.videoWidth||720;canvas.height=video.videoHeight||1280;const draw=()=>{if(!recording)return;ctx.save();ctx.filter=chosenFilter.css;ctx.drawImage(video,0,0,canvas.width,canvas.height);ctx.restore();requestAnimationFrame(draw)};const cs=canvas.captureStream(30);stream.getAudioTracks().forEach(t=>cs.addTrack(t));const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'';const r=new MediaRecorder(cs,mime?{mimeType:mime}:undefined);chunksRef.current=[];r.ondataavailable=e=>e.data.size&&chunksRef.current.push(e.data);r.onstop=()=>{const blob=new Blob(chunksRef.current,{type:r.mimeType||'video/webm'});const file=new File([blob],`kuzu-${Date.now()}.webm`,{type:blob.type});setRecordedFile(file);setCameraVideo(URL.createObjectURL(blob));cs.getTracks().forEach(t=>t.stop());setRecording(false)};recRef.current=r;setRecording(true);r.start();draw()}
 function stopRecording(){recRef.current?.stop()}
 function useRecording(){if(!recordedFile)return;const input=document.querySelector('input[name="video"]');if(input){const dt=new DataTransfer();dt.items.add(recordedFile);input.files=dt.files}setCameraOpen(false);stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 return <div className="modal"><form className="card upload" onSubmit={e=>{e.currentTarget.dataset.visibility=visibility;e.currentTarget.dataset.filter=filter;e.currentTarget.dataset.music=music;onSubmit(e)}}><button type="button" className="x" onClick={onClose}>×</button><h2>Create your KUZU video</h2><p className="muted">Open the camera, choose a filter, add licensed Bhutan music, then post.</p><div className="creatorTools"><button type="button" className="toolBtn" onClick={openCamera}>📷 Open Camera</button><label className="toolBtn">📁 Choose Video<input name="video" type="file" accept="video/*" required/></label></div>
 <div className="sectionTitle">✨ Camera filters</div><div className="filterRow">{CAMERA_FILTERS.map(f=><button type="button" key={f.id} className={filter===f.id?'filterBtn active':'filterBtn'} onClick={()=>setFilter(f.id)}><span style={{filter:f.css}}>◉</span>{f.name}</button>)}</div>
 <div className="sectionTitle">🎵 Bhutan Trending Music</div><div className="musicList"><button type="button" className={music==='none'?'musicItem active':'musicItem'} onClick={()=>setMusic('none')}><b>Original sound</b><small>Use your video's own audio</small></button>{BHUTAN_MUSIC.map(m=><button type="button" key={m.id} className={music===m.id?'musicItem active':'musicItem'} onClick={()=>setMusic(m.id)}><b>🎵 {m.title}</b><small>{m.artist} • {m.kind}</small></button>)}</div><p className="muted musicNote">KUZU should only publish music that it has permission to use. The tracks above are library slots for licensed/cleared Bhutan music; actual audio files can be connected to the KUZU music library.</p>
 {recordedFile&&<div className="recordedOk">✓ Camera video ready with <b>{chosenFilter.name}</b> filter{music!=='none'?' + selected music':''}</div>}
 <textarea name="caption" maxLength="500" placeholder="Write a caption..."/><input name="tags" maxLength="300" placeholder="#Bhutan #KUZU #travel"/><input name="location" maxLength="100" placeholder="📍 Add location (optional)"/><input name="mentions" maxLength="300" placeholder="@mention creators (optional)"/><div className="sectionTitle">Who can see this video?</div><div className="choices">{[['public','🌐 Public','Everyone can see this video'],['friends','👥 Friends only','Only mutual friends can see it'],['private','🔒 Private','Only you can see this video']].map(([v,t,d])=><button type="button" className={visibility===v?'choice active':'choice'} onClick={()=>setVisibility(v)} key={v}><b>{t}</b><small>{d}</small></button>)}</div><label className="check"><input name="allowComments" type="checkbox" defaultChecked/> Allow comments</label><label className="check"><input name="allowDownload" type="checkbox"/> Allow downloads</label><label className="check"><input name="allowDuet" type="checkbox" defaultChecked/> Allow remix / duet</label><button className="primary">Post video</button></form>
 {cameraOpen&&<div className="cameraOverlay"><div className="cameraCard"><button className="x" onClick={()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null);setCameraOpen(false)}}>×</button><h2>📷 KUZU Camera</h2><div className="cameraPreview"><video ref={videoRef} playsInline muted style={{filter:chosenFilter.css}}/><canvas ref={canvasRef} className="hiddenCanvas"/><div className="cameraFilterName">{chosenFilter.name}</div></div><div className="cameraControls"><button type="button" className="filterScroll" onClick={()=>{const i=CAMERA_FILTERS.findIndex(f=>f.id===filter);setFilter(CAMERA_FILTERS[(i+1)%CAMERA_FILTERS.length].id)}}>✨ Filter</button>{recording?<button type="button" className="recordBtn recording" onClick={stopRecording}>■ Stop</button>:<button type="button" className="recordBtn" onClick={startRecording}>● Record</button>}</div>{recordedFile&&<button type="button" className="primary" onClick={useRecording}>✓ Use This Video</button>}</div></div>}
 </div>
}

function Comments({comments,onSubmit,onClose,user}){return <div className="modal"><div className="card comments"><button className="x" onClick={onClose}>×</button><h2>Comments</h2><div className="commentList">{comments.length?comments.map(c=><div className="comment" key={c.id}><b>@{c.username}</b><span>{c.text}</span></div>):<p className="muted">No comments yet.</p>}</div>{user?<form onSubmit={onSubmit} className="commentForm"><input name="text" placeholder="Add a comment..."/><button>Send</button></form>:<button className="primary" onClick={()=>onClose()}>Sign in to comment</button>}</div></div>}
function Notifications({items}){return <section className="panel"><div className="panelHead"><h2>Notifications</h2><span>{items.filter(x=>!x.read).length} new</span></div>{items.length?items.map(n=><div className="notif" key={n.id}><div className="notifIcon">{n.type==='like'?'♥':n.type==='comment'?'💬':n.type==='follow'?'👤':'🔔'}</div><div><b>{n.text}</b><small>{new Date(n.createdAt).toLocaleString()}</small></div></div>):<div className="empty">No notifications yet.</div>}</section>}
function Messages({people,activeChat,chatMessages,onOpen,onSend}){return <section className="messagesPanel"><div className="people"><h2>Messages</h2>{people.length?people.map(p=><button className={activeChat===p.userId?'person active':''} key={p.userId} onClick={()=>onOpen(p.userId)}><span className="avatar">{(p.username||'?')[0].toUpperCase()}</span><span><b>@{p.username}</b><small>{p.lastMessage||'Start a conversation'}</small></span></button>):<div className="empty">Follow creators and start conversations.</div>}</div><div className="chat">{activeChat?<><div className="chatHead">Conversation</div><div className="chatList">{chatMessages.map(m=><div className={m.mine?'bubble mine':'bubble'} key={m.id}>{m.text}</div>)}</div><form className="chatForm" onSubmit={onSend}><input name="text" placeholder="Message..." autoComplete="off"/><button>Send</button></form></>:<div className="empty">Select a conversation.</div>}</div></section>}
function Profile({user,data,onLogout}){return <section className="profile"><div className="banner"/><div className="profileCard"><div className="bigAvatar">{(user.username||'K')[0].toUpperCase()}</div><h2>@{user.username}</h2><p>{user.bio||'Welcome to my KUZU profile 🇧🇹'}</p><div className="stats"><span><b>{user.followers||0}</b> Followers</span><span><b>{user.following||0}</b> Following</span><span><b>{data?.videos?.length||0}</b> Videos</span></div><button className="ghost" onClick={()=>window.dispatchEvent(new CustomEvent('kuzu-security'))}>Account security</button><button className="ghost" onClick={onLogout}>Sign out</button></div><div className="profileTabs"><span>Home</span><span>Videos</span><span>Liked</span><span>Saved</span></div><div className="grid">{data?.videos?.map(v=><video key={v.id} src={v.media} muted controls/> )}</div></section>}
function LiveHub({user,onLogin,onStart,onWatch,liveRoom,liveGiftLog}){
 const [giftsOpen,setGiftsOpen]=useState(false);
 const [gifts,setGifts]=useState(liveGiftLog||[]);
 const [rooms,setRooms]=useState([{id:'demo-live',username:'KUZU Gaming',title:'PUBG Mobile — Bhutan Gaming Live 🇧🇹',mode:'gaming',viewers:128,live:true}]);
 const [selected,setSelected]=useState(null);
 async function refresh(){try{const d=await api('live');if(d.rooms?.length)setRooms(d.rooms)}catch{}}
 useEffect(()=>{refresh()},[]);
 return <section className="liveHub"><div className="liveHero"><div><span className="liveBadge">● LIVE</span><h1>Go Live on KUZU</h1><p>Play a game, share your screen, invite friends and receive Bhutan-themed gifts while you stream.</p></div><button className="primary liveStart" onClick={onStart}>＋ Start Live</button></div>
  <div className="liveModes"><button onClick={onStart}>📹 Camera Live</button><button onClick={onStart}>🎮 Game Live</button><button onClick={onStart}>🖥️ Screen Share</button><button onClick={onStart}>👥 Live with Friends</button></div>
  <h2>Live now</h2><div className="liveGrid">{rooms.map(r=><button className="liveTile" key={r.id} onClick={()=>{setSelected(r);onWatch(r)}}><div className="liveThumb">{r.mode==='gaming'?'🎮':'📹'}<span>● LIVE</span></div><div className="liveTileInfo"><b>{r.title}</b><small>@{r.username} • {r.viewers} watching</small></div></button>)}</div>
  {liveRoom&&<LiveViewer room={liveRoom} onClose={()=>onWatch(null)} onGift={()=>setGiftsOpen(true)} giftLog={gifts}/>} {giftsOpen&&<GiftPicker room={liveRoom||selected||rooms[0]} onClose={()=>setGiftsOpen(false)} onSent={(gift)=>{setGifts(x=>[...x,{...gift,from:user?.username||'Viewer'}]);setGiftsOpen(false)}}/>} 
 </section>
}

function GiftReceiveAnimation({gift,onDone}){
 const [visible,setVisible]=useState(!!gift);
 useEffect(()=>{if(!gift)return;setVisible(true);const t=setTimeout(()=>{setVisible(false);onDone?.()},3600);return()=>clearTimeout(t)},[gift,onDone]);
 if(!gift||!visible)return null;
 const id=gift.id||'';
 let kind='gift-pop';
 if(id.includes('dragon')||id==='druk')kind='gift-dragon';
 else if(id==='blue-poppy')kind='gift-flower';
 else if(id==='red-panda')kind='gift-panda';
 else if(id==='prayer-flags')kind='gift-flags';
 else if(id==='takin'||id==='yak')kind='gift-animal';

 else if(id==='taktsang'||id==='mountains')kind='gift-mountain';
 else if(id==='tsechu-mask')kind='gift-mask';
 return <div className={`giftReceive ${kind}`} aria-live="polite">
   <div className="giftBurst">✦</div><div className="giftParticles">✦ · ✧ · ✦</div>
   <div className="giftCardReceive"><div className="giftFrom">🎁 @{gift.from||'Gifter'} sent a gift</div><div className="giftVisual">{gift.icon}</div><strong>{gift.name}</strong><small>Thank you for supporting the live!</small></div>
 </div>
}

function LiveViewer({room,onClose,onGift,giftLog}){
 const [received,setReceived]=useState(null);
 const seenRef=useRef(0);
 useEffect(()=>{if(giftLog.length>seenRef.current){const g=giftLog[giftLog.length-1];setReceived(g);seenRef.current=giftLog.length}},[giftLog]);
 return <div className="liveViewer"><div className="liveViewerTop"><button onClick={onClose}>← Back</button><span className="liveBadge">● LIVE</span><b>{room.viewers||0} watching</b></div><div className="liveViewerScreen"><div className="fakeGame">🎮<strong>{room.title}</strong><small>Live gameplay / screen share preview</small></div><div className="liveChat"><b>Live chat</b><div className="chatLines"><span><b>@Tashi:</b> KuZu! 🔥</span><span><b>@Pema:</b> Nice clutch!</span><span><b>@Sonam:</b> Bhutan 🇧🇹</span>{giftLog.map((g,i)=><span key={i}>🎁 <b>@{g.from}</b> sent {g.name}</span>)}</div><div className="giftBar"><button onClick={onGift}>🎁 Send Gift</button><button onClick={()=>navigator.share?navigator.share({title:room.title,url:location.href}):null}>↗ Share</button></div></div></div><GiftReceiveAnimation gift={received} onDone={()=>setReceived(null)}/></div>}

function GiftPicker({room,onClose,onSent}){const [sent,setSent]=useState(null);async function send(g){setSent(g);try{if(room?.id&&!String(room.id).startsWith('demo-'))await api(`live/${room.id}/gift`,{method:'POST',headers:jsonHeaders,body:JSON.stringify({giftId:g.id,name:g.name,cost:g.cost})});}catch{}onSent(g)}return <div className="modal"><div className="card giftCard"><button className="x" onClick={onClose}>×</button><h2>🎁 KUZU Live Gifts</h2><p className="muted">Bhutan-inspired gifts for live creators.</p><div className="giftGrid">{LIVE_GIFTS.map(g=><button className="giftItem" key={g.id} onClick={()=>send(g)}><span>{g.icon}</span><b>{g.name}</b><small>🪙 {g.cost}</small></button>)}</div>{sent&&<div className="giftSent">Sent {sent.icon} {sent.name}!</div>}</div></div>}

function LiveStudio({user,mode,setMode,onClose,onStarted,onNotice}){
 const videoRef=useRef(null),streamRef=useRef(null),recRef=useRef(null); const [status,setStatus]=useState('ready'); const [title,setTitle]=useState('PUBG Mobile Gaming Live 🇧🇹'); const [mic,setMic]=useState(true); const [share,setShare]=useState(mode==='gaming'||mode==='screen'); const [elapsed,setElapsed]=useState(0);
 useEffect(()=>{let t;if(status==='live')t=setInterval(()=>setElapsed(x=>x+1),1000);return()=>clearInterval(t)},[status]);
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(t=>t.stop());recRef.current?.stop()},[]);
 async function start(){try{let base;if(share){if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Screen sharing is not supported by this browser/device. Try Chrome or a supported desktop browser.');base=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});if(mic&&navigator.mediaDevices.getUserMedia){const m=await navigator.mediaDevices.getUserMedia({audio:true});m.getAudioTracks().forEach(t=>base.addTrack(t))}}else{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera/microphone access is not available here.');base=await navigator.mediaDevices.getUserMedia({video:true,audio:mic});}
 streamRef.current=base;if(videoRef.current){videoRef.current.srcObject=base;videoRef.current.muted=true;await videoRef.current.play().catch(()=>{})}base.getVideoTracks()[0]?.addEventListener('ended',stop);setStatus('live');setElapsed(0);onNotice('Live Studio started. Screen/game capture is active on this device.')}catch(e){onNotice(e.message||'Could not start live capture.')}}
 function stop(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setStatus('ready');onNotice('Live capture stopped.')} 
 async function finish(){if(status!=='live')return;stop();try{const d=await api('live',{method:'POST',headers:jsonHeaders,body:JSON.stringify({action:'start',title,mode:share?'gaming':'camera'})});onStarted(d.room)}catch{onStarted({id:'local-'+Date.now(),username:user.username,title,mode:share?'gaming':'camera',viewers:1,live:true})}}
 const mm=String(Math.floor(elapsed/60)).padStart(2,'0'),ss=String(elapsed%60).padStart(2,'0');
 return <div className="modal"><div className="card studio"><button className="x" onClick={onClose}>×</button><div className="studioHead"><div><span className="liveBadge">KUZU LIVE STUDIO</span><h2>{status==='live'?'You are live':'Create a live'}</h2></div><span className="timer">{mm}:{ss}</span></div><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Live title"/><div className="modeChoices"><button className={mode==='camera'?'active':''} onClick={()=>{setMode('camera');setShare(false)}}>📹 Camera</button><button className={mode==='gaming'?'active':''} onClick={()=>{setMode('gaming');setShare(true)}}>🎮 Game + Screen</button><button className={mode==='screen'?'active':''} onClick={()=>{setMode('screen');setShare(true)}}>🖥️ Screen Share</button></div><div className="studioPreview"><video ref={videoRef} playsInline muted/><div className="previewLabel">{status==='live'?(share?'🎮 Game/screen is being captured':'📹 Camera live preview'):'Preview'}</div></div><div className="studioControls"><label><input type="checkbox" checked={mic} onChange={e=>setMic(e.target.checked)}/> 🎙️ Mic</label><span>🎮 Start the game after screen sharing begins</span></div><div className="studioNote">Game Live uses your device's screen-share permission. You can open PUBG Mobile or another game after starting the screen share. Actual multi-viewer broadcast delivery needs a live streaming/WebRTC service; this build prepares the live studio and gift experience.</div>{status==='live'?<button className="primary" onClick={finish}>🔴 Finish & Create Live Room</button>:<button className="primary" onClick={start}>▶ Start {share?'Screen/Game Capture':'Camera Live'}</button>}</div></div>
}

createRoot(document.getElementById('root')).render(<App/>);
